[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "edwh-web2py-effdted-prio-grid"
description = 'Web2py plugin for a effective dated grid with priority support.'
readme = "README.md"
requires-python = ">=3.10"
license-expression = "MIT"
keywords = ['web2py', 'grid', 'effective-dated', 'effdt']
authors = [
    { name = "Remco Boerma", email = "remco.b@educationwarehouse.nl" },
    { name = "Romy Schöller", email = "romy.s@educationwarehouse.nl" },
    { name = "Robin van der Noord", email = "robin.vdn@educationwarehouse.nl" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []
version = "0.6.3"

[project.optional-dependencies]
dev = [
    "web2py-gluon",
]

[project.urls]
Documentation = "https://github.com/educationwarehouse/edwh-web2py-effdted-prio-grid#readme"
Issues = "https://github.com/educationwarehouse/edwh-web2py-effdted-prio-grid/issues"
Source = "https://github.com/educationwarehouse/edwh-web2py-effdted-prio-grid"

[tool.vommit]
allow_breaking_bang = true
allow_breaking_footer = true
prerelease_token = "beta"
confirm = true
ignore = []

[tool.vommit.git]
enabled = true
origin = "origin"
branch = "master"
on_wrong_branch = "error"
tag_format = "v{version}"
commit_format = "{version}"

[tool.vommit.changelog]
enabled = true
file = "CHANGELOG.md"
include_prereleases = false
placeholder = "<!--next-version-placeholder-->"
placeholder_regex = "<auto>"
entry_title_format = "## v{version} ({date:%Y-%m-%d})"

[tool.vommit.changelog.levels]
feat = "Feature{s}"
fix = "Fix{es}"
break = "Breaking Change{s}"
docs = "Documentation"
perf = "Performance"

[tool.vommit.pypi]
enabled = true
use_keyring = true

[tool.vommit.commands]
clean = "rm -rf ./dist"
build = "uv build"
publish = "uv publish"
post_publish = ""

[tool.vommit.version_bump_map]
break = "major"
build = "patch"
chore = "patch"
feat = "minor"
fix = "patch"
perf = "patch"
refactor = "patch"

[tool.black]
target-version = ["py310"]
line-length = 120
skip-string-normalization = false

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = [
    "A",
    "ARG",
    "B",
    "C",
    "DTZ",
    "E",
    "EM",
    "F",
    "I",
    "ICN",
    "ISC",
    "N",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "Q",
    "RUF",
    "S",
    "T",
    "TID",
    "W",
    "YTT",
]
ignore = [
    # Allow non-abstract empty methods in abstract base classes
    "B027",
    # Ignore checks for possible passwords
    "S105", "S106", "S107",
    # Ignore complexity
    "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
    # pydal
    "E712",
    # f-string in exception:
    "EM102",
]
unfixable = [
    # Don't touch unused imports
    "F401",
]

[tool.ruff.lint.isort]
known-first-party = ["edwh_web2py_effdted_prio_grid"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]

[tool.coverage.run]
source_pkgs = ["edwh_web2py_effdted_prio_grid", "tests"]
branch = true
parallel = true
omit = [
    "src/edwh_web2py_effdted_prio_grid/__about__.py",
]

[tool.coverage.paths]
edwh_web2py_effdted_prio_grid = ["src/edwh_web2py_effdted_prio_grid", "*/edwh-web2py-effdted-prio-grid/src/edwh_web2py_effdted_prio_grid"]
tests = ["tests", "*/edwh-web2py-effdted-prio-grid/tests"]

[tool.coverage.report]
exclude_lines = [
    "no cov",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
